package com.goku.coreui.sys.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.goku.coreui.sys.model.FlourmillCompany;
import com.goku.coreui.sys.model.SysUser;

public interface FlourmillCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flourmill_company
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flourmill_company
     *
     * @mbg.generated
     */
    int insert(FlourmillCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flourmill_company
     *
     * @mbg.generated
     */
    int insertSelective(FlourmillCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flourmill_company
     *
     * @mbg.generated
     */
    FlourmillCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flourmill_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FlourmillCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table flourmill_company
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FlourmillCompany record);
    
    List<FlourmillCompany> getCompanyForPaging(@Param("companyName")String companyName,
            @Param("orderFiled") String orderFiled, @Param("orderSort") String orderSort);
    
}