package com.goku.coreui.sys.model;

import java.util.Date;

public class FlourmillCompany {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flourmill_company.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flourmill_company.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flourmill_company.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column flourmill_company.id_del
     *
     * @mbg.generated
     */
    private Integer idDel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flourmill_company.id
     *
     * @return the value of flourmill_company.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flourmill_company.id
     *
     * @param id the value for flourmill_company.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flourmill_company.company_name
     *
     * @return the value of flourmill_company.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flourmill_company.company_name
     *
     * @param companyName the value for flourmill_company.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flourmill_company.create_time
     *
     * @return the value of flourmill_company.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flourmill_company.create_time
     *
     * @param createTime the value for flourmill_company.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column flourmill_company.id_del
     *
     * @return the value of flourmill_company.id_del
     *
     * @mbg.generated
     */
    public Integer getIdDel() {
        return idDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column flourmill_company.id_del
     *
     * @param idDel the value for flourmill_company.id_del
     *
     * @mbg.generated
     */
    public void setIdDel(Integer idDel) {
        this.idDel = idDel;
    }
}